# Generated by Django 4.2.2 on 2023-06-09 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='valor_respuesta',
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.pregunta')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.test')),
            ],
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.pregunta'),
        ),
    ]
