# Generated by Django 4.2.2 on 2023-06-14 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpcionRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opcion", models.CharField(max_length=255)),
                ("valor", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="respuesta",
        ),
        migrations.RemoveField(
            model_name="pregunta",
            name="valor_respuesta",
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carrera", models.CharField(max_length=100)),
                ("instituto", models.CharField(max_length=100)),
                ("edad", models.CharField(max_length=100)),
                ("sexo", models.IntegerField()),
                ("semestre", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Respuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opcion_respuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.opcionrespuesta",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.pregunta",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="libreria.test"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="opcionrespuesta",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="libreria.pregunta"
            ),
        ),
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calificacion", models.IntegerField()),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="libreria.test"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="libreria.usuario",
                    ),
                ),
            ],
        ),
    ]
