
INSERT INTO libreria_test (nombre, descripcion) VALUES ('Audit', 'Test de evaluación del consumo de alcohol');

INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria) VALUES
    (1, '¿Qué tan frecuentemente ingiere bebidas alcohólicas?', 'opciones', 'consumo'),
    (1, 'Durante el último año, ¿qué tan frecuentemente bebió a la mañana siguiente después de haber bebido en exceso el día anterior?', 'opciones', 'consumo'),
    (1, '¿Cuántas copas se toma en un día típico o común de los que bebe?', 'opciones', 'consumo'),
    (1, 'Durante el último año, ¿qué tan frecuentemente se sintió culpable o tuvo remordimiento por haber bebido?', 'opciones', 'emocional'),
    (1, '¿Qué tan frecuentemente toma seis o más copas en la misma ocasión?', 'opciones', 'consumo'),
    (1, 'Durante el último año, ¿qué tan frecuentemente olvidó algo de lo que había pasado cuando estuvo bebiendo?', 'opciones', 'memoria'),
    (1, 'Durante el último año, ¿le ocurrió que no pudo parar de beber una vez que había empezado?', 'opciones', 'control'),
    (1, '¿Se ha lastimado o alguien ha resultado lastimado como consecuencia de su ingestión de alcohol?', 'opciones', 'consecuencias'),
    (1, 'Durante el último año, ¿qué tan frecuentemente dejó de hacer algo que debería haber hecho por beber?', 'opciones', 'comportamiento'),
    (1, '¿Algún amigo, familiar o doctor se ha preocupado por la forma en que bebe o le ha sugerido que le baje?', 'opciones', 'apoyo');

INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor) VALUES
    (1, 'Nunca', 0),
    (1, 'Una vez al mes o menos', 1),
    (1, 'De 2 a 4 veces por mes', 2),
    (1, '2 o 3 veces por semana', 3),
    (2, 'Nunca', 0),
    (2, 'Menos de una vez al mes', 1),
    (2, 'Mensualmente', 2),
    (2, 'Semanalmente', 3),
    (2, 'Diario o casi diario', 4),
    (3, 'Una o dos', 0),
    (3, 'Tres o cuatro', 1),
    (3, 'Cinco o seis', 2),
    (3, 'De siete a nueve', 3),
    (3, 'Diez o más', 4),
    (4, 'Nunca', 0),
    (4, 'Menos de una vez al mes', 1),
    (4, 'Mensualmente', 2),
    (4, 'Semanalmente', 3),
    (4, 'Diario o casi diario', 4),
    (5, 'Nunca', 0),
    (5, 'Menos de una vez al mes', 1),
    (5, 'Mensualmente', 2),
    (5, 'Semanalmente', 3),
    (5, 'Diario o casi diario', 4),
    (6, 'Nunca', 0),
    (6, 'Menos de una vez al mes', 1),
    (6, 'Mensualmente', 2),
    (6, 'Semanalmente', 3),
    (6, 'Diario o casi diario', 4),
    (7, 'Nunca', 0),
    (7, 'Menos de una vez al mes', 1),
    (7, 'Mensualmente', 2),
    (7, 'Semanalmente', 3),
    (7, 'Diario o casi diario', 4),
    (8, 'No', 0),
    (8, 'Sí, pero no en el último año', 1),
    (8, 'Sí, en el último año', 2),
    (9, 'Nunca', 0),
    (9, 'Menos de una vez al mes', 1),
    (9, 'Mensualmente', 2),
    (9, 'Semanalmente', 3),
    (9, 'Diario o casi diario', 4),
    (10, 'No', 0),
    (10, 'Sí, pero no en el último año', 1),
    (10, 'Sí, en el último año', 2);


INSERT INTO libreria_test (nombre, descripcion) VALUES ('PHQ-9', 'Test de evaluación de la depresión PHQ-9');

INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria) VALUES
    (2, 'Tener poco interés o placer en hacer las cosas', 'opciones', 'depresion'),
    (2, 'Sentirse desanimado/a, deprimido/a, o sin esperanza', 'opciones', 'depresion'),
    (2, 'Con problemas en dormirse o en mantenerse dormido/a, o en dormir demasiado', 'opciones', 'sueno'),
    (2, 'Sentirse cansado/a o tener poca energía', 'opciones', 'energia'),
    (2, 'Tener poco apetito o comer en exceso', 'opciones', 'alimentacion'),
    (2, 'Sentir falta de amor propio-o que sea un fracaso o que decepcionara a sí mismo/a su familia', 'opciones', 'autoestima'),
    (2, 'Tener dificultad para concentrarse en cosas tales como leer el periódico o mirar televisión', 'opciones', 'concentracion'),
    (2, 'Se mueve o habla tan lentamente que otra gente se podría dar cuenta- o de lo contrario, está tan agitado/a o inquieto/a que se mueve mucho más de lo acostumbrado', 'opciones', 'movimiento'),
    (2, 'Se le han ocurrido pensamientos de que sería mejor estar muerto/a o de que haría daño de alguna manera', 'opciones', 'pensamientos');

INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor) VALUES
    (11, 'Nunca', 0),
    (11, 'Varios días', 1),
    (11, 'Más de la mitad de los días', 2),
    (11, 'Casi todos los días', 3),
    (12, 'Nunca', 0),
    (12, 'Varios días', 1),
    (12, 'Más de la mitad de los días', 2),
    (12, 'Casi todos los días', 3),
    (13, 'Nunca', 0),
    (13, 'Varios días', 1),
    (13, 'Más de la mitad de los días', 2),
    (13, 'Casi todos los días', 3),
    (14, 'Nunca', 0),
    (14, 'Varios días', 1),
    (14, 'Más de la mitad de los días', 2),
    (14, 'Casi todos los días', 3),
    (15, 'Nunca', 0),
    (15, 'Varios días', 1),
    (15, 'Más de la mitad de los días', 2),
    (15, 'Casi todos los días', 3),
    (16, 'Nunca', 0),
    (16, 'Varios días', 1),
    (16, 'Más de la mitad de los días', 2),
    (16, 'Casi todos los días', 3),
    (17, 'Nunca', 0),
    (17, 'Varios días', 1),
    (17, 'Más de la mitad de los días', 2),
    (17, 'Casi todos los días', 3),
    (18, 'Nunca', 0),
    (18, 'Varios días', 1),
    (18, 'Más de la mitad de los días', 2),
    (18, 'Casi todos los días', 3),
    (19, 'Nunca', 0),
    (19, 'Varios días', 1),
    (19, 'Más de la mitad de los días', 2),
    (19, 'Casi todos los días', 3);

INSERT INTO libreria_test (nombre, descripcion) VALUES ('MDQ', 'Test Mood Disorder Questionnaire');

INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria) VALUES
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… se sintió bien o con el ánimo tan elevado, o tan “hiperactivo “, que algunos pensaron que usted no era la misma persona de siempre; o estuvo tan animado o “hiperactivo”, ¿qué se metió en problemas o en dificultades?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… estaba tan irritable, que le gritaba a la gente; ¿o iniciaba peleas o discusiones?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… se sentía mucho más seguro de sí mismo que otras veces?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… dormía mucho menos que de costumbre, pero notaba que no sentía falta de sueño?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… hablaba mucho más, o mucho más rápido que de costumbre?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… le pasaban las ideas muy rápidamente por la cabeza o no podía pensar lentamente?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… se distraía muy fácilmente por las cosas que sucedían a su alrededor, al punto de que necesitaba hacer un gran esfuerzo en concentrarse o en continuar lo que estaba haciendo?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… tenía más energía que de costumbre?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… estaba mucho más activo o hacía muchas más cosas que de costumbre?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… era socialmente mucho más activo y comunicativo, al punto de que –por ejemplo– telefoneaba a amistades en medio de la noche?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… se interesaba en el sexo más que de costumbre?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… hacía cosas que no eran comunes en usted, o que la gente podía haber considerado excesivas, tontas o arriesgadas?', 'opciones', 'mood'),
    (3, '¿Le sucedió alguna vez que por un cierto período usted comenzó a sentirse o actuar diferente de cómo era, y… el gastar dinero le causó problemas a usted o su familia?', 'opciones', 'mood'),
    (3, 'Si usted marcó sí más de una vez, ¿ocurrieron varias de esas situaciones todas juntas en un mismo tiempo?', 'opciones', 'mood'),
    (3, '¿Cuántas dificultades le causaron cualquiera de las situaciones mencionadas (por ejemplo, no poder trabajar, problemas familiares, de dinero o legales; enfrascarse en discusiones o peleas)? Por favor marque solo una de las siguientes respuestas.', 'opciones', 'mood');

INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor) VALUES
    (20, 'Sí', 1),
    (20, 'No', 0),
    (21, 'Sí', 1),
    (21, 'No', 0),
    (22, 'Sí', 1),
    (22, 'No', 0),
    (23, 'Sí', 1),
    (23, 'No', 0),
    (24, 'Sí', 1),
    (24, 'No', 0),
    (25, 'Sí', 1),
    (25, 'No', 0),
    (26, 'Sí', 1),
    (26, 'No', 0),
    (27, 'Sí', 1),
    (27, 'No', 0),
    (28, 'Sí', 1),
    (28, 'No', 0),
    (29, 'Sí', 1),
    (29, 'No', 0),
    (30, 'Sí', 1),
    (30, 'No', 0),
    (31, 'Sí', 1),
    (31, 'No', 0),
    (32, 'Sí', 1),
    (32, 'No', 0),
    (33, 'Sí', 1),
    (33, 'No', 0),
    (34, 'Ningún problema', 0),
    (34, 'Problema menor', 1),
    (34, 'Problema moderado', 2),
    (34, 'Problema serio', 3);

INSERT INTO libreria_test (nombre, descripcion) VALUES ('DEP-ADO', 'Test de evaluación del consumo de drogas y alcohol');


INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria) VALUES
    (4, 'Durante los últimos 12 meses, ¿has consumido alguno de estos productos?', 'opciones', 'consumo'),
    (4, 'Si es así, ¿Cuál ha sido la frecuencia de tu consumo?', 'opciones', 'consumo'),
    (4, '¿Has consumido alguna vez en forma regular alguno de los productos señalados en la pregunta anterior? (por lo menos una vez por semana durante un mes)', 'opciones', 'consumo'),
    (4, '¿A qué edad comenzaste a consumir regularmente Alcohol?', 'opciones', 'consumo'),
    (4, '¿A qué edad comenzaste a consumir regularmente Una o varias drogas?', 'opciones', 'consumo'),
    (4, 'Durante tu vida ¿Te has inyectado drogas alguna vez?', 'opciones', 'consumo'),
    (4, '¿Has consumido alcohol en los últimos 30 días?', 'opciones', 'consumo'),
    (4, '¿Has consumido otras drogas en los últimos 30 días?', 'opciones', 'consumo'),
    (4, 'En los últimos 12 meses, ¿cuántas veces has consumido 8 tragos de alcohol (hombres) / 6 tragos (mujeres), o más en una misma ocasión? Un trago es igual a una lata de cerveza, una copa de vino o un vaso de combinado simple (MINSAL, 2011)', 'opciones', 'consumo'),
    (4, 'En los últimos 12 meses, ¿te han sucedido algunas de las siguientes situaciones?', 'opciones', 'consumo'),
    (4, '¿Cuál ha sido tu consumo de Tabaco en los últimos 12 meses?', 'opciones', 'consumo');


INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor) VALUES
    (35, 'Alcohol', 0),
    (35, 'Marihuana (yerba, pito, huiro, macoña)', 1),
    (35, 'Pasta Base de Cocaína (Mono, bazuco, pasta)', 2),
    (35, 'Cocaína (Coca, haley, raya, línea)', 3),
    (35, 'Pegamento / Solvente (Neopren, bencina, laca)', 4),
    (35, 'Alucinógenos (éxtasis, peyote, LSD, floripondio)', 5),
    (35, 'Anfetaminas (anfeta, pepa, ritalín)', 6),
    (35, 'Otros (Medicamentos tomados sin receta: antidepresivos, hipnóticos, etc.)', 7),
    (36, 'No a consumido', 0),
    (36, 'En ocasiones', 1),
    (36, 'Alrededor De una vez al mes', 2),
    (36, 'El fin de semana o una o dos veces en la semana', 3),
    (36, '3 veces y más en la semana pero no todos los días', 4),
    (36, 'Todos los días', 5),
    (37, 'Si', 1),
    (37, 'No', 0),
    (38, 'Años', 0),
    (39, 'Años', 0),
    (40, 'Si', 1),
    (40, 'No', 0),
    (41, 'Si', 1),
    (41, 'No', 0),
    (42, 'Si', 1),
    (42, 'No', 0),
    (43, 'Si', 1),
    (43, 'No', 0),
    (44, 'Si', 1),
    (44, 'No', 0),
    (45, 'Sin Consumo', 0),
    (45, 'El fin de semana o una a dos veces por semana', 1),
    (45, 'En ocasiones', 2),
    (45, '3 veces o más por semana pero no todos los días', 3),
    (45, 'Alrededor de una vez al mes', 4),
    (45, 'Todos los días', 5);

-- Inserción en la tabla libreria_test
INSERT INTO libreria_test (nombre, descripcion)
VALUES ('EDDS', 'Test para evaluar la relación con la comida y los trastornos alimentarios');
INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria)
VALUES
    (5, 'En los últimos 3 meses ¿Te has sentido gordo?', 'opciones', 'peso'),
    (5, 'En los últimos 3 meses ¿Ha tenido una fe definitiva de que podría subir de peso o engordar?', 'opciones', 'peso'),
    (5, 'En los últimos 3 meses ¿Ha influido su peso en cómo piensa en (juzga) a sí mismo como persona?', 'opciones', 'peso'),
    (5, 'En los últimos 3 meses ¿Tu forma ha influido en cómo piensas (juzgas) sobre ti mismo como persona?', 'opciones', 'peso'),
    (5, 'Durante los últimos 6 meses ¿ha habido momentos en los que sintió que había comido lo que otras personas considerarían una cantidad inusualmente grande de alimentos (por ejemplo, un litro de helado) dadas las circunstancias?', 'opciones', 'comportamiento'),
    (5, 'Durante los momentos en que usted ha comido una cantidad inusualmente grande de alimentos, ¿ha experimentado una pérdida de control (sintió que no podía dejar de comer o controlar qué o cuánto estaba comiendo)?', 'opciones', 'comportamiento'),
    (5, '¿Cuántos DÍAS a la semana en promedio durante los últimos 6 MESES ha comido una cantidad inusualmente grande de alimentos y ha perdido el control?', 'opciones', 'comportamiento'),
    (5, '¿Cuántas VECES por semana en promedio durante los últimos 6 MESES ha comido una cantidad inusualmente grande de alimentos y ha perdido el control?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted Come mucho más rápido de lo normal?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted Comió hasta que se sintió incómodamente lleno?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted Comió grandes cantidades de alimentos cuando no se sentía físicamente hambriento?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted Comía solo porque le daba vergüenza lo mucho que comía?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted Está disgustado consigo mismo, deprimido o muy culpable después de comer en exceso?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted Se siente muy molesto por comer en exceso de forma incontrolable o por el aumento de peso resultante?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted ¿Cuántas veces por semana en promedio durante los últimos 3 meses se ha hecho vomitar para prevenir el aumento de peso o contrarrestar el efecto de comer?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted ¿Cuántas veces por semana en promedio durante los últimos 3 meses ha usado laxantes o diuréticos para prevenir el aumento de peso o contrarrestar los efectos de comer?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted ¿Cuántas veces por semana en promedio durante los últimos 3 meses ha ayunado (omitido al menos 2 comidas seguidas) para prevenir el aumento de peso o contrarrestar los efectos de comer?', 'opciones', 'comportamiento'),
    (5, 'Durante estos episodios de comer en exceso y perder el control, ¿usted ¿Cuántas veces por semana en promedio durante los últimos 3 meses ha realizado ejercicio excesivo específicamente para contrarrestar los efectos de los episodios de sobrealimentación?', 'opciones', 'comportamiento'),
    (5, '¿Cuánto pesa?', 'numero', 'peso'),
    (5, '¿Cuánto mide?', 'numero', 'peso');


INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor)
VALUES
    (46, 'Siempre', 5),
    (46, 'Normalmente', 4),
    (46, 'A menudo', 3),
    (46, 'Algunas veces', 2),
    (46, 'Raramente', 1),
    (46, 'Nunca', 0),
    (47, 'Siempre', 5),
    (47, 'Normalmente', 4),
    (47, 'A menudo', 3),
    (47, 'Algunas veces', 2),
    (47, 'Raramente', 1),
    (47, 'Nunca', 0),
    (48, 'Siempre', 5),
    (48, 'Normalmente', 4),
    (48, 'A menudo', 3),
    (48, 'Algunas veces', 2),
    (48, 'Raramente', 1),
    (48, 'Nunca', 0),
    (49, 'Siempre', 5),
    (49, 'Normalmente', 4),
    (49, 'A menudo', 3),
    (49, 'Algunas veces', 2),
    (49, 'Raramente', 1),
    (49, 'Nunca', 0);

INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor)
VALUES
    (50, 'SÍ', 1),
    (50, 'NO', 0),
    (51, 'SÍ', 1),
    (51, 'NO', 0),

    (52, '0', 0),
    (52, '1', 1),
    (52, '2', 2),
    (52, '3', 3),
    (52, '4', 4),
    (52, '5', 5),
    (52, '6', 6),
    (52, '7', 7),

    (53, '0', 0),
    (53, '1', 1),
    (53, '2', 2),
    (53, '3', 3),
    (53, '4', 4),
    (53, '5', 5),
    (53, '6', 6),
    (53, '7', 7),

    (54, 'SÍ', 1),
    (54, 'NO', 0),
    (55, 'SÍ', 1),
    (55, 'NO', 0),
    (56, 'SÍ', 1),
    (56, 'NO', 0),
    (57, 'SÍ', 1),
    (57, 'NO', 0),
    (58, 'SÍ', 1),
    (58, 'NO', 0),
    (59, 'SÍ', 1),
    (59, 'NO', 0),
    
    (60, '0', 0),
    (60, '1', 1),
    (60, '2', 2),
    (60, '3', 3),
    (60, '4', 4),
    (60, '5', 5),
    (60, '6', 6),
    (60, '7', 7),

    (61, '0', 0),
    (61, '1', 1),
    (61, '2', 2),
    (61, '3', 3),
    (61, '4', 4),
    (61, '5', 5),
    (61, '6', 6),
    (61, '7', 7),

    (62, '0', 0),
    (62, '1', 1),
    (62, '2', 2),
    (62, '3', 3),
    (62, '4', 4),
    (62, '5', 5),
    (62, '6', 6),
    (62, '7', 7),

    (63, '0', 0),
    (63, '1', 1),
    (63, '2', 2),
    (63, '3', 3),
    (63, '4', 4),
    (63, '5', 5),
    (63, '6', 6),
    (63, '7', 7),
    (64, 'peso', NULL),
    (65, 'centímetros', NULL);


INSERT INTO libreria_test (nombre, descripcion)
VALUES ('BHS', 'Escala de Desesperanza de Beck. Evalúa la actitud y perspectiva hacia el futuro de una persona, así como su nivel de desesperanza');

INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria)
VALUES
(6, 'Espero el futuro con esperanza y entusiasmo', 'opciones', 'actitud'),
(6, 'Puedo darme por vencido, renunciar, ya que no puedo hacer mejor las cosas por mí mismo', 'opciones', 'actitud'),
(6, 'Cuando las cosas van mal me alivia saber que las cosas no pueden permanecer tiempo así', 'opciones', 'actitud'),
(6, 'No puedo imaginar cómo será mi vida dentro de 10 años', 'opciones', 'actitud'),
(6, 'Tengo bastante tiempo para llevar a cabo las cosas que quisiera poder hacer', 'opciones', 'actitud'),
(6, 'En el futuro espero poder conseguir los que me pueda interesar', 'opciones', 'actitud'),
(6, 'Mi futuro me parece oscuro', 'opciones', 'actitud'),
(6, 'Espero más cosas buenas de la vida que lo que la gente suele conseguir por término medio', 'opciones', 'actitud'),
(6, 'No logro hacer que las cosas cambien y no existen razones para creer que pueda en el futuro', 'opciones', 'actitud'),
(6, 'Mis pasadas experiencias me han preparado bien para mi futuro', 'opciones', 'actitud'),
(6, 'Todo lo que puedo ver hacia adelante es más desagradable que agradable', 'opciones', 'actitud'),
(6, 'No espero conseguir lo que realmente deseo', 'opciones', 'actitud'),
(6, 'Cuando miro hacia el futuro espero que seré más feliz de lo que soy ahora', 'opciones', 'actitud'),
(6, 'Las cosas no marchan como yo quisiera', 'opciones', 'actitud'),
(6, 'Tengo una gran confianza en el futuro', 'opciones', 'actitud'),
(6, 'Nunca consigo lo que deseo, por lo que es absurdo desear cualquier cosa', 'opciones', 'actitud'),
(6, 'Es muy improbable que pueda lograr una satisfacción real en el futuro', 'opciones', 'actitud'),
(6, 'El futuro me parece vago e incierto', 'opciones', 'actitud'),
(6, 'Espero más bien épocas buenas que malas', 'opciones', 'actitud'),
(6, 'No merece la pena que intente conseguir algo que desee, porque probablemente no lo lograré', 'opciones', 'actitud');

INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor)
VALUES
    (66, 'Verdadero', 1),
    (66, 'Falso', 0),
    (67, 'Verdadero', 1),
    (67, 'Falso', 0),
    (68, 'Verdadero', 1),
    (68, 'Falso', 0),
    (69, 'Verdadero', 1),
    (69, 'Falso', 0),
    (70, 'Verdadero', 1),
    (70, 'Falso', 0),
    (71, 'Verdadero', 1),
    (71, 'Falso', 0),
    (72, 'Verdadero', 1),
    (72, 'Falso', 0),
    (73, 'Verdadero', 1),
    (73, 'Falso', 0),
    (74, 'Verdadero', 1),
    (74, 'Falso', 0),
    (75, 'Verdadero', 1),
    (75, 'Falso', 0),
    (76, 'Verdadero', 1),
    (76, 'Falso', 0),
    (77, 'Verdadero', 1),
    (77, 'Falso', 0),
    (78, 'Verdadero', 1),
    (78, 'Falso', 0),
    (79, 'Verdadero', 1),
    (79, 'Falso', 0),
    (80, 'Verdadero', 1),
    (80, 'Falso', 0),
    (81, 'Verdadero', 1),
    (81, 'Falso', 0),
    (82, 'Verdadero', 1),
    (82, 'Falso', 0),
    (83, 'Verdadero', 1),
    (83, 'Falso', 0),
    (84, 'Verdadero', 1),
    (84, 'Falso', 0),
    (85, 'Verdadero', 1),
    (85, 'Falso', 0);

-- Inserción del test "Ansiedad"
INSERT INTO libreria_test (nombre, descripcion)
VALUES ('Ansiedad', 'Escala de Ansiedad. Evalúa los niveles de ansiedad en diferentes situaciones y contextos');

-- Inserción de las preguntas del test "Ansiedad"
INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria)
VALUES
(7, 'Molestan mis propios latidos', 'opciones', 'ansiedad'),
(7, 'Me cuesta decir que no cuando me piden algo prestado', 'opciones', 'ansiedad'),
(7, 'Me irrito y me pongo nervioso/a por cosas sin importancia', 'opciones', 'ansiedad'),
(7, 'Me es muy difícil decir que no a un vendedor', 'opciones', 'ansiedad'),
(7, 'Sin razón aparente, a veces siento miedo y aprensión', 'opciones', 'ansiedad'),
(7, 'Suelo rehusar las invitaciones a citas o reuniones', 'opciones', 'ansiedad'),
(7, 'Me preocupo demasiado y eso me desanima', 'opciones', 'ansiedad'),
(7, 'No sé cómo decirle a un/a amigo/a íntimo/a que algo me molesta de él/ella', 'opciones', 'ansiedad'),
(7, 'Me siento totalmente cansado', 'opciones', 'ansiedad'),
(7, 'Me es muy difícil hacer reclamaciones o exigir algo', 'opciones', 'ansiedad'),
(7, 'Me resulta laborioso tomar decisiones', 'opciones', 'ansiedad'),
(7, 'Suelo callarme si no estoy de acuerdo con mi interlocutor', 'opciones', 'ansiedad'),
(7, 'Siempre tengo miedo a tomar decisiones', 'opciones', 'ansiedad'),
(7, 'No me gusta recibir cumplidos', 'opciones', 'ansiedad'),
(7, 'Tengo casi siempre los nervios de punta', 'opciones', 'ansiedad'),
(7, 'Me es difícil mantener una conversación con alguien o con quien no estoy de acuerdo', 'opciones', 'ansiedad'),
(7, 'Muchas veces pienso que no seré capaz de resolver mis problemas', 'opciones', 'ansiedad'),
(7, 'Si alguien me pide un favor con insistencia, casi nunca me niego', 'opciones', 'ansiedad'),
(7, 'Siempre estoy bajo presión y tensión', 'opciones', 'ansiedad'),
(7, 'Cuando no entiendo algo, se me hace difícil hacer preguntas en público', 'opciones', 'ansiedad');

-- Inserción de las opciones de respuesta del test "Ansiedad"
INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor)
VALUES
    (86, 'Muy pocas veces', 1),
    (86, 'Algun tiempo', 2),
    (86, 'Gran parte del tiempo', 3),
    (86, 'Casi siempre', 4),
    (87, 'Muy pocas veces', 1),
    (87, 'Algun tiempo', 2),
    (87, 'Gran parte del tiempo', 3),
    (87, 'Casi siempre', 4),
    (88, 'Muy pocas veces', 1),
    (88, 'Algun tiempo', 2),
    (88, 'Gran parte del tiempo', 3),
    (88, 'Casi siempre', 4),
    (89, 'Muy pocas veces', 1),
    (89, 'Algun tiempo', 2),
    (89, 'Gran parte del tiempo', 3),
    (89, 'Casi siempre', 4),
    (90, 'Muy pocas veces', 1),
    (90, 'Algun tiempo', 2),
    (90, 'Gran parte del tiempo', 3),
    (90, 'Casi siempre', 4),
    (91, 'Muy pocas veces', 1),
    (91, 'Algun tiempo', 2),
    (91, 'Gran parte del tiempo', 3),
    (91, 'Casi siempre', 4),
    (92, 'Muy pocas veces', 1),
    (92, 'Algun tiempo', 2),
    (92, 'Gran parte del tiempo', 3),
    (92, 'Casi siempre', 4),
    (93, 'Muy pocas veces', 1),
    (93, 'Algun tiempo', 2),
    (93, 'Gran parte del tiempo', 3),
    (93, 'Casi siempre', 4),
    (94, 'Muy pocas veces', 1),
    (94, 'Algun tiempo', 2),
    (94, 'Gran parte del tiempo', 3),
    (94, 'Casi siempre', 4),
    (95, 'Muy pocas veces', 1),
    (95, 'Algun tiempo', 2),
    (95, 'Gran parte del tiempo', 3),
    (95, 'Casi siempre', 4),
    (96, 'Muy pocas veces', 1),
    (96, 'Algun tiempo', 2),
    (96, 'Gran parte del tiempo', 3),
    (96, 'Casi siempre', 4),
    (97, 'Muy pocas veces', 1),
    (97, 'Algun tiempo', 2),
    (97, 'Gran parte del tiempo', 3),
    (97, 'Casi siempre', 4),
    (98, 'Muy pocas veces', 1),
    (98, 'Algun tiempo', 2),
    (98, 'Gran parte del tiempo', 3),
    (98, 'Casi siempre', 4),
    (99, 'Muy pocas veces', 1),
    (99, 'Algun tiempo', 2),
    (99, 'Gran parte del tiempo', 3),
    (99, 'Casi siempre', 4),
    (100, 'Muy pocas veces', 1),
    (100, 'Algun tiempo', 2),
    (100, 'Gran parte del tiempo', 3),
    (100, 'Casi siempre', 4),
    (101, 'Muy pocas veces', 1),
    (101, 'Algun tiempo', 2),
    (101, 'Gran parte del tiempo', 3),
    (101, 'Casi siempre', 4),
    (102, 'Muy pocas veces', 1),
    (102, 'Algun tiempo', 2),
    (102, 'Gran parte del tiempo', 3),
    (102, 'Casi siempre', 4),
    (103, 'Muy pocas veces', 1),
    (103, 'Algun tiempo', 2),
    (103, 'Gran parte del tiempo', 3),
    (103, 'Casi siempre', 4),
    (104, 'Muy pocas veces', 1),
    (104, 'Algun tiempo', 2),
    (104, 'Gran parte del tiempo', 3),
    (104, 'Casi siempre', 4),
    (105, 'Muy pocas veces', 1),
    (105, 'Algun tiempo', 2),
    (105, 'Gran parte del tiempo', 3),
    (105, 'Casi siempre', 4);

INSERT INTO libreria_test (nombre, descripcion)
VALUES ('Estrés', 'Cuestionario para evaluar el nivel de estrés en una persona');

INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria)
VALUES
(8, 'Busco la naturaleza en mi tiempo libre', 'opciones', 'hábitos'),
(8, 'Tomo bebidas alcohólicas', 'opciones', 'hábitos'),
(8, 'Como abundantes frutas y verduras', 'opciones', 'hábitos'),
(8, 'Fumo', 'opciones', 'hábitos'),
(8, 'Hago ejercicio de forma regular', 'opciones', 'hábitos'),
(8, 'Tomo tranquilizantes habitualmente', 'opciones', 'hábitos'),
(8, 'Vivo en una casa limpia y ordenada', 'opciones', 'entorno'),
(8, 'Vivo en un barrio ruidoso', 'opciones', 'entorno'),
(8, 'Disfruto del ambiente hogareño', 'opciones', 'entorno'),
(8, 'Hay demasiada gente a mi alrededor', 'opciones', 'entorno'),
(8, 'Gozo de un buen apetito', 'opciones', 'físico'),
(8, 'Empiezo a ser olvidadizo/a', 'opciones', 'físico'),
(8, 'Hago bien las digestiones', 'opciones', 'físico'),
(8, 'Me siento fatigado/a sin razón aparente', 'opciones', 'físico'),
(8, 'Duermo bien', 'opciones', 'físico'),
(8, 'Me irrito con facilidad', 'opciones', 'emocional'),
(8, 'Me llevo bien con mis superiores', 'opciones', 'emocional'),
(8, 'Utilizo el automóvil como medio de trabajo', 'opciones', 'emocional'),
(8, 'Tengo trabajo estable', 'opciones', 'emocional'),
(8, 'Me tengo que llevar el trabajo a casa', 'opciones', 'emocional'),
(8, 'Me llevo bien con mis compañeros y amigos', 'opciones', 'social'),
(8, 'Me impacienta mucho cuando alguien se demora', 'opciones', 'social'),
(8, 'Se escuchar con paciencia', 'opciones', 'social'),
(8, 'Hablo demasiado', 'opciones', 'social'),
(8, 'Me siento a gusto con mi vida sexual', 'opciones', 'sexual'),
(8, 'Me propongo hacer las cosas mejor que otros', 'opciones', 'mental'),
(8, 'Me agrada mi manera de ser', 'opciones', 'mental'),
(8, 'Soy perfeccionista', 'opciones', 'mental'),
(8, 'Tengo buen sentido del humor', 'opciones', 'mental'),
(8, 'Me irrita hacer cola', 'opciones', 'situacional');

INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor)
VALUES
    (106, 'Muy pocas veces', 1),
    (106, 'Algun tiempo', 2),
    (106, 'Gran parte del tiempo', 3),
    (106, 'Casi siempre', 4),
    (107, 'Muy pocas veces', 1),
    (107, 'Algun tiempo', 2),
    (107, 'Gran parte del tiempo', 3),
    (107, 'Casi siempre', 4),
    (108, 'Muy pocas veces', 1),
    (108, 'Algun tiempo', 2),
    (108, 'Gran parte del tiempo', 3),
    (108, 'Casi siempre', 4),
    (109, 'Muy pocas veces', 1),
    (109, 'Algun tiempo', 2),
    (109, 'Gran parte del tiempo', 3),
    (109, 'Casi siempre', 4),
    (110, 'Muy pocas veces', 1),
    (110, 'Algun tiempo', 2),
    (110, 'Gran parte del tiempo', 3),
    (110, 'Casi siempre', 4),
    (111, 'Muy pocas veces', 1),
    (111, 'Algun tiempo', 2),
    (111, 'Gran parte del tiempo', 3),
    (111, 'Casi siempre', 4),
    (112, 'Muy pocas veces', 1),
    (112, 'Algun tiempo', 2),
    (112, 'Gran parte del tiempo', 3),
    (112, 'Casi siempre', 4),
    (113, 'Muy pocas veces', 1),
    (113, 'Algun tiempo', 2),
    (113, 'Gran parte del tiempo', 3),
    (113, 'Casi siempre', 4),
    (114, 'Muy pocas veces', 1),
    (114, 'Algun tiempo', 2),
    (114, 'Gran parte del tiempo', 3),
    (114, 'Casi siempre', 4),
    (115, 'Muy pocas veces', 1),
    (115, 'Algun tiempo', 2),
    (115, 'Gran parte del tiempo', 3),
    (115, 'Casi siempre', 4),
    (116, 'Muy pocas veces', 1),
    (116, 'Algun tiempo', 2),
    (116, 'Gran parte del tiempo', 3),
    (116, 'Casi siempre', 4),
    (117, 'Muy pocas veces', 1),
    (117, 'Algun tiempo', 2),
    (117, 'Gran parte del tiempo', 3),
    (117, 'Casi siempre', 4),
    (118, 'Muy pocas veces', 1),
    (118, 'Algun tiempo', 2),
    (118, 'Gran parte del tiempo', 3),
    (118, 'Casi siempre', 4),
    (119, 'Muy pocas veces', 1),
    (119, 'Algun tiempo', 2),
    (119, 'Gran parte del tiempo', 3),
    (119, 'Casi siempre', 4),
    (120, 'Muy pocas veces', 1),
    (120, 'Algun tiempo', 2),
    (120, 'Gran parte del tiempo', 3),
    (120, 'Casi siempre', 4),
    (121, 'Muy pocas veces', 1),
    (121, 'Algun tiempo', 2),
    (121, 'Gran parte del tiempo', 3),
    (121, 'Casi siempre', 4),
    (122, 'Muy pocas veces', 1),
    (122, 'Algun tiempo', 2),
    (122, 'Gran parte del tiempo', 3),
    (122, 'Casi siempre', 4),
    (123, 'Muy pocas veces', 1),
    (123, 'Algun tiempo', 2),
    (123, 'Gran parte del tiempo', 3),
    (123, 'Casi siempre', 4),
    (124, 'Muy pocas veces', 1),
    (124, 'Algun tiempo', 2),
    (124, 'Gran parte del tiempo', 3),
    (124, 'Casi siempre', 4),
    (125, 'Muy pocas veces', 1),
    (125, 'Algun tiempo', 2),
    (125, 'Gran parte del tiempo', 3),
    (125, 'Casi siempre', 4),
    (126, 'Muy pocas veces', 1),
    (126, 'Algun tiempo', 2),
    (126, 'Gran parte del tiempo', 3),
    (126, 'Casi siempre', 4),
    (127, 'Muy pocas veces', 1),
    (127, 'Algun tiempo', 2),
    (127, 'Gran parte del tiempo', 3),
    (127, 'Casi siempre', 4),
    (128, 'Muy pocas veces', 1),
    (128, 'Algun tiempo', 2),
    (128, 'Gran parte del tiempo', 3),
    (128, 'Casi siempre', 4),
    (129, 'Muy pocas veces', 1),
    (129, 'Algun tiempo', 2),
    (129, 'Gran parte del tiempo', 3),
    (129, 'Casi siempre', 4),
    (130, 'Muy pocas veces', 1),
    (130, 'Algun tiempo', 2),
    (130, 'Gran parte del tiempo', 3),
    (130, 'Casi siempre', 4),
    (131, 'Muy pocas veces', 1),
    (131, 'Algun tiempo', 2),
    (131, 'Gran parte del tiempo', 3),
    (131, 'Casi siempre', 4),
    (132, 'Muy pocas veces', 1),
    (132, 'Algun tiempo', 2),
    (132, 'Gran parte del tiempo', 3),
    (132, 'Casi siempre', 4),
    (133, 'Muy pocas veces', 1),
    (133, 'Algun tiempo', 2),
    (133, 'Gran parte del tiempo', 3),
    (133, 'Casi siempre', 4),
    (134, 'Muy pocas veces', 1),
    (134, 'Algun tiempo', 2),
    (134, 'Gran parte del tiempo', 3),
    (134, 'Casi siempre', 4),
    (135, 'Muy pocas veces', 1),
    (135, 'Algun tiempo', 2),
    (135, 'Gran parte del tiempo', 3),
    (135, 'Casi siempre', 4);

-- Inserción del Test 9 - Afección Académica
INSERT INTO libreria_test (nombre, descripcion)
VALUES ('Afección Académica', 'Evalúa la afectación académica debido a problemas emocionales o de estrés');

-- Inserción de las preguntas del Test 9 - Afección Académica
INSERT INTO libreria_pregunta (test_id, pregunta, tipo_pregunta, categoria)
VALUES
(9, 'Este problema afecta mi desarrollo académico', 'opciones', 'afeccion'),
(9, 'Este problema me impide aprender', 'opciones', 'afeccion'),
(9, 'No puedo estudiar porque me preocupa tener esta situación personal', 'opciones', 'afeccion'),
(9, 'Creo que mis calificaciones han bajado por el estrés que presento', 'opciones', 'afeccion'),
(9, 'La problemática que presento podría motivarme a desertar de mi carrera', 'opciones', 'afeccion'),
(9, 'Considero que puedo superar los problemas emocionales o de estrés que presento', 'opciones', 'afeccion'),
(9, 'En los últimos exámenes que he presentado tengo bajas calificaciones', 'opciones', 'afeccion'),
(9, 'Estoy reprobado(a) en algunos exámenes presentados porque mis problemas me impiden estudiar', 'opciones', 'afeccion'),
(9, 'Haciendo un gran esfuerzo mejoraré mis calificaciones', 'opciones', 'afeccion'),
(9, 'La deserción de la carrera sería el último recurso que aplicaría si no mejoro esta condición problemática', 'opciones', 'afeccion');

-- Inserción de las opciones de respuesta para el Test 9 - Afección Académica
INSERT INTO libreria_opcionrespuesta (pregunta_id, opcion, valor)
VALUES
    (136, 'Totalmente en desacuerdo', 1),
    (136, 'En desacuerdo', 2),
    (136, 'Ni de acuerdo ni en desacuerdo', 3),
    (136, 'De acuerdo', 4),
    (136, 'Totalmente de acuerdo', 5),
    (137, 'Totalmente en desacuerdo', 1),
    (137, 'En desacuerdo', 2),
    (137, 'Ni de acuerdo ni en desacuerdo', 3),
    (137, 'De acuerdo', 4),
    (137, 'Totalmente de acuerdo', 5),
    (138, 'Totalmente en desacuerdo', 1),
    (138, 'En desacuerdo', 2),
    (138, 'Ni de acuerdo ni en desacuerdo', 3),
    (138, 'De acuerdo', 4),
    (138, 'Totalmente de acuerdo', 5),
    (139, 'Totalmente en desacuerdo', 1),
    (139, 'En desacuerdo', 2),
    (139, 'Ni de acuerdo ni en desacuerdo', 3),
    (139, 'De acuerdo', 4),
    (139, 'Totalmente de acuerdo', 5),
    (140, 'Totalmente en desacuerdo', 1),
    (140, 'En desacuerdo', 2),
    (140, 'Ni de acuerdo ni en desacuerdo', 3),
    (140, 'De acuerdo', 4),
    (140, 'Totalmente de acuerdo', 5),
    (141, 'Totalmente en desacuerdo', 1),
    (141, 'En desacuerdo', 2),
    (141, 'Ni de acuerdo ni en desacuerdo', 3),
    (141, 'De acuerdo', 4),
    (141, 'Totalmente de acuerdo', 5),
    (142, 'Totalmente en desacuerdo', 1),
    (142, 'En desacuerdo', 2),
    (142, 'Ni de acuerdo ni en desacuerdo', 3),
    (142, 'De acuerdo', 4),
    (142, 'Totalmente de acuerdo', 5),
    (143, 'Totalmente en desacuerdo', 1),
    (143, 'En desacuerdo', 2),
    (143, 'Ni de acuerdo ni en desacuerdo', 3),
    (143, 'De acuerdo', 4),
    (143, 'Totalmente de acuerdo', 5),
    (144, 'Totalmente en desacuerdo', 1),
    (144, 'En desacuerdo', 2),
    (144, 'Ni de acuerdo ni en desacuerdo', 3),
    (144, 'De acuerdo', 4),
    (144, 'Totalmente de acuerdo', 5),
    (145, 'Totalmente en desacuerdo', 1),
    (145, 'En desacuerdo', 2),
    (145, 'Ni de acuerdo ni en desacuerdo', 3),
    (145, 'De acuerdo', 4),
    (145, 'Totalmente de acuerdo', 5);

